### ISSUE TITLE
named export createI18n not found when trying to build 

### ISSUE THREAD

**Issue by MagedAhmad** [boussadjra/vueye#5] opened 2023-03-01 08:32 UTC
Works fine with `pnpm dev` but when i try to run `pnpm build` i get this message error

```
import { createI18n, useI18n } from "vue-i18n/dist/vue-i18n.runtime.esm-bundler.js";
         ^^^^^^^^^^
SyntaxError: Named export 'createI18n' not found. The requested module 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export
```

**Comment by boussadjra** [comment] 2023-03-01 08:35
@MagedAhmad  I'll try to reproduce the issue later

**Comment by boussadjra** [comment] 2023-03-04 08:49
The issue is fixed by adding 
`  ssr: {
    noExternal: [/vue-i18n/],
  },`
 to vite.config.ts
Try to clone the project again, there're also other fixes

**Closed as completed by boussadjra** 2023-03-04 08:49 UTC
